from __future__ import annotations

import json
import math
import time
from pathlib import Path

import joblib

import optimize_gesture_model as experiment


def find_app_dir() -> Path:
    script = Path(__file__).resolve()
    for base in (script.parents[1], script.parents[2]):
        for project_root in (
            base / "VeriHealthi_QEMU_SDK_v3.7",
            base / "01_完整工程" / "VeriHealthi_QEMU_SDK_v3.7",
        ):
            candidate = project_root / "galaxy_sdk" / "app"
            if candidate.is_dir():
                return candidate
    return script.parents[1] / "VeriHealthi_QEMU_SDK_v3.7" / "galaxy_sdk" / "app"


APP_DIR = find_app_dir()
MODEL_PATH = Path(__file__).resolve().parent / "gesture_rf_final.joblib"
METADATA_PATH = Path(__file__).resolve().parent / "gesture_rf_final.json"

TREE_COUNT = 100
MAX_DEPTH = 14
MIN_SAMPLES_LEAF = 2
FEATURE_COUNT = 123

POSTPROCESS = {
    "pinch_votes": 82,
    "clench_votes": 77,
    "up_votes": 50,
    "down_votes": 50,
    "confirm_windows": 3,
    "cooldown_ms": 600,
    "release_windows": 2,
    "arm_state": True,
}


def format_array(values: list[int], per_line: int) -> str:
    return "\n".join(
        "    " + ", ".join(str(value) for value in values[start : start + per_line]) + ","
        for start in range(0, len(values), per_line)
    )


def export_c_model(model) -> dict[str, int]:
    offsets: list[int] = []
    left: list[int] = []
    right: list[int] = []
    feature: list[int] = []
    threshold: list[int] = []
    value: list[int] = []

    for estimator in model.estimators_:
        tree = estimator.tree_
        if tree.node_count >= 0xFFFF:
            raise ValueError("tree has too many nodes for uint16 child indices")
        offsets.append(len(left))
        for node_id in range(tree.node_count):
            left_child = int(tree.children_left[node_id])
            right_child = int(tree.children_right[node_id])
            if left_child < 0:
                left.append(0xFFFF)
                right.append(0xFFFF)
                feature.append(0)
                threshold.append(0)
                value.append(int(tree.value[node_id][0].argmax()))
            else:
                left.append(left_child)
                right.append(right_child)
                feature.append(int(tree.feature[node_id]))
                threshold.append(math.floor(float(tree.threshold[node_id])))
                value.append(0)

    header = f'''/* Generated by algorithm_sim/train_final_model.py. */

#ifndef APP_GESTURE_RF_MODEL_H
#define APP_GESTURE_RF_MODEL_H

#include <stdint.h>
#include "gesture_algo.h"

#define GESTURE_RF_FEATURE_COUNT {FEATURE_COUNT}U
#define GESTURE_RF_TREE_COUNT {len(offsets)}U
#define GESTURE_RF_NODE_COUNT {len(left)}UL

typedef struct GestureRfFeatures_st {{
    int32_t value[GESTURE_RF_FEATURE_COUNT];
}} GestureRfFeatures;

GestureType gesture_rf_predict_with_votes(const GestureRfFeatures *features,
                                          uint8_t votes[5]);

#endif
'''

    source = f'''/* Generated by algorithm_sim/train_final_model.py. */

#include "gesture_rf_model.h"

#include <stddef.h>

#define RF_LEAF_NODE 0xFFFFU

static const uint32_t g_tree_offsets[GESTURE_RF_TREE_COUNT] = {{
{format_array(offsets, 8)}
}};

static const uint16_t g_left[GESTURE_RF_NODE_COUNT] = {{
{format_array(left, 16)}
}};

static const uint16_t g_right[GESTURE_RF_NODE_COUNT] = {{
{format_array(right, 16)}
}};

static const uint8_t g_feature[GESTURE_RF_NODE_COUNT] = {{
{format_array(feature, 20)}
}};

static const int32_t g_threshold[GESTURE_RF_NODE_COUNT] = {{
{format_array(threshold, 10)}
}};

static const uint8_t g_value[GESTURE_RF_NODE_COUNT] = {{
{format_array(value, 20)}
}};

GestureType gesture_rf_predict_with_votes(const GestureRfFeatures *features,
                                          uint8_t votes[5])
{{
    uint32_t tree_id;
    uint8_t best_class = 0U;

    if (!features || !votes) {{
        return GESTURE_NONE;
    }}

    for (tree_id = 0U; tree_id < 5U; tree_id++) {{
        votes[tree_id] = 0U;
    }}

    for (tree_id = 0U; tree_id < GESTURE_RF_TREE_COUNT; tree_id++) {{
        uint32_t offset = g_tree_offsets[tree_id];
        uint16_t node = 0U;

        while (g_left[offset + node] != RF_LEAF_NODE) {{
            uint8_t feature_index = g_feature[offset + node];
            if (features->value[feature_index] <= g_threshold[offset + node]) {{
                node = g_left[offset + node];
            }} else {{
                node = g_right[offset + node];
            }}
        }}
        votes[g_value[offset + node]]++;
    }}

    for (tree_id = 1U; tree_id < 5U; tree_id++) {{
        if (votes[tree_id] > votes[best_class]) {{
            best_class = (uint8_t)tree_id;
        }}
    }}
    return (GestureType)best_class;
}}
'''

    (APP_DIR / "gesture_rf_model.h").write_text(header, encoding="ascii", newline="\n")
    (APP_DIR / "gesture_rf_model.c").write_text(source, encoding="ascii", newline="\n")
    return {
        "tree_count": len(offsets),
        "node_count": len(left),
        "estimated_model_bytes": len(offsets) * 4 + len(left) * 10,
    }


def main() -> None:
    started = time.perf_counter()
    recordings = experiment.load_recordings()
    features, labels = experiment.build_training_set(
        recordings, window_samples=50, rich=True, dynamic=True
    )
    model = experiment.make_model(
        "rf", TREE_COUNT, MAX_DEPTH, MIN_SAMPLES_LEAF, seed=2026, jobs=-1
    )
    experiment.fit_model(model, features, labels)
    model_info = export_c_model(model)
    joblib.dump(model, MODEL_PATH, compress=3)

    metadata = {
        "sample_rate_hz": experiment.SAMPLE_RATE_HZ,
        "window_samples": 50,
        "window_step_samples": experiment.WINDOW_STEP_SAMPLES,
        "feature_count": features.shape[1],
        "training_windows": len(features),
        "class_counts": {
            name: int((labels == label_id).sum())
            for label_id, name in enumerate(experiment.CLASS_NAMES)
        },
        "random_forest": {
            "trees": TREE_COUNT,
            "max_depth": MAX_DEPTH,
            "min_samples_leaf": MIN_SAMPLES_LEAF,
            "random_state": 2026,
        },
        "postprocess": POSTPROCESS,
        **model_info,
        "elapsed_seconds": round(time.perf_counter() - started, 3),
    }
    METADATA_PATH.write_text(
        json.dumps(metadata, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(json.dumps(metadata, indent=2, ensure_ascii=False))
    print(f"wrote {APP_DIR / 'gesture_rf_model.c'}")
    print(f"wrote {APP_DIR / 'gesture_rf_model.h'}")
    print(f"wrote {MODEL_PATH}")
    print(f"wrote {METADATA_PATH}")


if __name__ == "__main__":
    main()
