/*
 * Generated by algorithm_sim/train_random_forest.py.
 */

#ifndef APP_GESTURE_RF_MODEL_H
#define APP_GESTURE_RF_MODEL_H

#include <stdint.h>
#include "gesture_algo.h"

#define GESTURE_RF_FEATURE_COUNT 22
#define GESTURE_RF_TREE_COUNT 25
#define GESTURE_RF_NODE_COUNT 7477

typedef struct GestureRfFeatures_st {
    int32_t value[GESTURE_RF_FEATURE_COUNT];
} GestureRfFeatures;

GestureType gesture_rf_predict(const GestureRfFeatures *features);
GestureType gesture_rf_predict_with_votes(const GestureRfFeatures *features, uint8_t *best_votes);

#endif
