/* Generated by algorithm_sim/train_final_model.py. */

#ifndef APP_GESTURE_RF_MODEL_H
#define APP_GESTURE_RF_MODEL_H

#include <stdint.h>
#include "gesture_algo.h"

#define GESTURE_RF_FEATURE_COUNT 123U
#define GESTURE_RF_TREE_COUNT 120U
#define GESTURE_RF_NODE_COUNT 427572UL

typedef struct GestureRfFeatures_st {
    int32_t value[GESTURE_RF_FEATURE_COUNT];
} GestureRfFeatures;

GestureType gesture_rf_predict_with_votes(const GestureRfFeatures *features,
                                          uint8_t votes[5]);

#endif
